import { Inter } from "next/font/google";
import { Nav, Footer, AppBanner } from "@/comps";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdn.tailwindcss.com" async></script>
      </head>
      <body className={inter.className}>
        <AppBanner />
        <Nav />
        <main className="min-h-[82.6vh]"> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
