import { AppBanner, Footer, Nav } from "@/comps";
import { ContextProvider } from "@/context/contextProvider";
import { Inter } from "next/font/google";
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdn.tailwindcss.com" async></script>
      </head>
      <body className="bg-white">
        <ContextProvider>
          <AppBanner />
          <Nav />
          <main className="min-h-[82.6vh]"> {children}</main>
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
